-- 코드를 입력하세요
SELECT B.FOOD_TYPE,
       B.REST_ID,
       B.REST_NAME,
       A.FAVORITES
FROM (
    SELECT FOOD_TYPE, MAX(FAVORITES) FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) A, REST_INFO B
WHERE A.FAVORITES = B.FAVORITES
AND A.FOOD_TYPE = B.FOOD_TYPE
ORDER BY B.FOOD_TYPE DESC