-- -- 코드를 입력하세요
SELECT B.PRODUCT_ID,
       B.PRODUCT_NAME,
       A.SUM_PRICE TOTAL_SALES
FROM(
    SELECT A.PRODUCT_ID, SUM(AMOUNT * PRICE) SUM_PRICE
    FROM FOOD_PRODUCT A, FOOD_ORDER B
    WHERE A.PRODUCT_ID = B.PRODUCT_ID(+)
    AND B.PRODUCE_DATE BETWEEN TO_DATE('20220501','YYYYMMDD') AND TO_DATE('20220531','YYYYMMDD')
    GROUP BY A.PRODUCT_ID
) A, FOOD_PRODUCT B
WHERE A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, B.PRODUCT_ID
