-- 코드를 입력하세요
SELECT B.CATEGORY , B.PRICE, B.PRODUCT_NAME
FROM(
    SELECT CATEGORY, MAX(PRICE) PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자','국','김치','식용유')
    GROUP BY CATEGORY
) A, FOOD_PRODUCT B
WHERE A.CATEGORY = B.CATEGORY
AND A.PRICE = B.PRICE
ORDER BY PRICE DESC